SOURCE = "_source"

ROIS = "proto_data_rois"
METADATA = "proto_data_metadata"
SENSOR_DATA = "proto_data_sensor_data"

MANUAL = "manual"
ALGORITHM = "algorithm"
ALGORITHM_VERSION = "algorithm_version"
TYPE = "type"
RECT = "rect"
TL = "tl"
BR = "br"
COL = "col"
ROW = "row"
DETECTIONS = "detections"
CONFIDENCE = "confidence"

TRIP_ID = "trip_id"
IMAGE_INDEX = "image_index"
IMAGE_PATH = "image_path"
REGION = "region"

SPEED = "speed_kmh"
TIMESTAMP = "timestamp"
RAW_POSITION = "raw_position"
LATITUDE = "latitude"
LONGITUDE = "longitude"
HEADING = "heading"

MATCH_DATA="proto_data_match_data"
MATCHED_POSITION= "matched_position"
MATCHED_HEADING= "matched_heading"
