# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orbb_camera_specification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='orbb_camera_specification.proto',
  package='orbb',
  syntax='proto2',
  serialized_pb=_b('\n\x1forbb_camera_specification.proto\x12\x04orbb\"\x8e\x01\n\tPhoneLens\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x02(\t\x12\x14\n\x0c\x66ocal_length\x18\x02 \x02(\x01\x12\x13\n\x0bpixel_width\x18\x03 \x02(\x01\x12\x14\n\x0cpixel_height\x18\x04 \x02(\x01\x12\x14\n\x0csensor_width\x18\x05 \x02(\x01\x12\x15\n\rsensor_height\x18\x06 \x02(\x01\"4\n\x0bPhoneLenses\x12%\n\x0cphone_lenses\x18\x01 \x03(\x0b\x32\x0f.orbb.PhoneLens')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PHONELENS = _descriptor.Descriptor(
  name='PhoneLens',
  full_name='orbb.PhoneLens',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_name', full_name='orbb.PhoneLens.device_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='focal_length', full_name='orbb.PhoneLens.focal_length', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pixel_width', full_name='orbb.PhoneLens.pixel_width', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pixel_height', full_name='orbb.PhoneLens.pixel_height', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensor_width', full_name='orbb.PhoneLens.sensor_width', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensor_height', full_name='orbb.PhoneLens.sensor_height', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=184,
)


_PHONELENSES = _descriptor.Descriptor(
  name='PhoneLenses',
  full_name='orbb.PhoneLenses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone_lenses', full_name='orbb.PhoneLenses.phone_lenses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=238,
)

_PHONELENSES.fields_by_name['phone_lenses'].message_type = _PHONELENS
DESCRIPTOR.message_types_by_name['PhoneLens'] = _PHONELENS
DESCRIPTOR.message_types_by_name['PhoneLenses'] = _PHONELENSES

PhoneLens = _reflection.GeneratedProtocolMessageType('PhoneLens', (_message.Message,), dict(
  DESCRIPTOR = _PHONELENS,
  __module__ = 'orbb_camera_specification_pb2'
  # @@protoc_insertion_point(class_scope:orbb.PhoneLens)
  ))
_sym_db.RegisterMessage(PhoneLens)

PhoneLenses = _reflection.GeneratedProtocolMessageType('PhoneLenses', (_message.Message,), dict(
  DESCRIPTOR = _PHONELENSES,
  __module__ = 'orbb_camera_specification_pb2'
  # @@protoc_insertion_point(class_scope:orbb.PhoneLenses)
  ))
_sym_db.RegisterMessage(PhoneLenses)


# @@protoc_insertion_point(module_scope)
