class MatchParams:
    PROBES = "probes"
    TIMESTAMP = "timestamp"
    LAT = "latitude"
    LON = "longitude"
    PROPERTIES = "properties"
    ACCURACY = "accuracy"
    HEADING = "heading"
    SPEED = "speedMPH"
    TIME_BASED_MATCHED_SECTIONS = "timeBasedMatchedSections"
    WAY_ID = "wayId"
    FROM_NODE_ID = "fromNodeId"
    TO_NODE_ID = "toNodeId"
    ID = "id"
    INDEX = "index"
    COMPUTED_HEADING = "computedHeading"
    MATCHED_POSITION = "matchedPosition"
    