class MatchColumn:
    FORWARD = "forward"
    WAY_ID = "way_id"
    FROM_NODE_ID = "from_node_id"
    TO_NODE_ID = "to_node_id"
    HEADING = "heading"
    MATCHED_LAT = "matched_lat"
    MATCHED_LON = "matched_lon"
    COMPUTED_HEADING = "computed_heading"
    OFFSET = "offset"
    DATETIME = "datetime"
    TIMESTAMP = "timestamp"
    LAT = "lat"
    LON = "lon"
