#!/bin/bash

echo ""
echo "Attempting to login to Azure Container Registry: $AZURE_CONTAINER_REGISTRY"

if [ "$1" == "test" ]; then
    echo "Simulated: az login --service-principal -u $SERVICE_PRINCIPAL_USERNAME -p $1 --tenant $SERVICE_PRINCIPAL_TENANT"
    echo "Simulated: docker login $AZURE_CONTAINER_REGISTRY_URL  -u $SERVICE_PRINCIPAL_USERNAME -p $1"
else
    az login --service-principal -u $SERVICE_PRINCIPAL_USERNAME -p $1 --tenant $SERVICE_PRINCIPAL_TENANT
    docker login $AZURE_CONTAINER_REGISTRY_URL -u $SERVICE_PRINCIPAL_USERNAME -p $1
fi