#!/bin/bash

# Make sure the following packages are installed
if ! pip list | grep 'GitPython'; then
    pip install gitpython
fi
if ! which az; then
    pip install --user azure-cli
fi

# Print the environment variables
env | sort