# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clustering.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import orbb_metadata_pb2 as orbb__metadata__pb2
import orbb_definitions_pb2 as orbb__definitions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='clustering.proto',
  package='orbb',
  syntax='proto2',
  serialized_pb=_b('\n\x10\x63lustering.proto\x12\x04orbb\x1a\x13orbb_metadata.proto\x1a\x16orbb_definitions.proto\"\x9f\x02\n\x0e\x43lusteredPoint\x12\x12\n\ncluster_id\x18\x01 \x01(\x03\x12\x1f\n\x08location\x18\x02 \x02(\x0b\x32\r.orbb.GPSPair\x12\x0e\n\x06\x66\x61\x63ing\x18\x03 \x02(\x02\x12\x18\n\x04type\x18\x04 \x02(\x0e\x32\n.orbb.Mark\x12\x12\n\nconfidence\x18\x06 \x02(\x02\x12%\n\x0cmatched_data\x18\x07 \x01(\x0b\x32\x0f.orbb.MatchData\x12\x0f\n\x07roi_ids\x18\x08 \x03(\x04\x12\x11\n\talgorithm\x18\t \x02(\t\x12\x19\n\x11\x61lgorithm_version\x18\n \x02(\t\x12\x34\n\x13matched_osm_element\x18\x0b \x01(\x0b\x32\x17.orbb.MatchedOsmElement\"1\n\x08\x43lusters\x12%\n\x07\x63luster\x18\x01 \x03(\x0b\x32\x14.orbb.ClusteredPoint\"\x9a\x01\n\x07GeoTile\x12\x1f\n\x08top_left\x18\x01 \x02(\x0b\x32\r.orbb.GPSPair\x12#\n\x0c\x62ottom_right\x18\x02 \x02(\x0b\x32\r.orbb.GPSPair\x12&\n\x08\x63lusters\x18\x03 \x03(\x0b\x32\x14.orbb.ClusteredPoint\x12!\n\timage_set\x18\x04 \x02(\x0b\x32\x0e.orbb.ImageSet')
  ,
  dependencies=[orbb__metadata__pb2.DESCRIPTOR,orbb__definitions__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CLUSTEREDPOINT = _descriptor.Descriptor(
  name='ClusteredPoint',
  full_name='orbb.ClusteredPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster_id', full_name='orbb.ClusteredPoint.cluster_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='orbb.ClusteredPoint.location', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='facing', full_name='orbb.ClusteredPoint.facing', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='orbb.ClusteredPoint.type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='orbb.ClusteredPoint.confidence', index=4,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='matched_data', full_name='orbb.ClusteredPoint.matched_data', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='roi_ids', full_name='orbb.ClusteredPoint.roi_ids', index=6,
      number=8, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='orbb.ClusteredPoint.algorithm', index=7,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='algorithm_version', full_name='orbb.ClusteredPoint.algorithm_version', index=8,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='matched_osm_element', full_name='orbb.ClusteredPoint.matched_osm_element', index=9,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=359,
)


_CLUSTERS = _descriptor.Descriptor(
  name='Clusters',
  full_name='orbb.Clusters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster', full_name='orbb.Clusters.cluster', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=410,
)


_GEOTILE = _descriptor.Descriptor(
  name='GeoTile',
  full_name='orbb.GeoTile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='top_left', full_name='orbb.GeoTile.top_left', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bottom_right', full_name='orbb.GeoTile.bottom_right', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clusters', full_name='orbb.GeoTile.clusters', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_set', full_name='orbb.GeoTile.image_set', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=567,
)

_CLUSTEREDPOINT.fields_by_name['location'].message_type = orbb__metadata__pb2._GPSPAIR
_CLUSTEREDPOINT.fields_by_name['type'].enum_type = orbb__definitions__pb2._MARK
_CLUSTEREDPOINT.fields_by_name['matched_data'].message_type = orbb__metadata__pb2._MATCHDATA
_CLUSTEREDPOINT.fields_by_name['matched_osm_element'].message_type = orbb__metadata__pb2._MATCHEDOSMELEMENT
_CLUSTERS.fields_by_name['cluster'].message_type = _CLUSTEREDPOINT
_GEOTILE.fields_by_name['top_left'].message_type = orbb__metadata__pb2._GPSPAIR
_GEOTILE.fields_by_name['bottom_right'].message_type = orbb__metadata__pb2._GPSPAIR
_GEOTILE.fields_by_name['clusters'].message_type = _CLUSTEREDPOINT
_GEOTILE.fields_by_name['image_set'].message_type = orbb__metadata__pb2._IMAGESET
DESCRIPTOR.message_types_by_name['ClusteredPoint'] = _CLUSTEREDPOINT
DESCRIPTOR.message_types_by_name['Clusters'] = _CLUSTERS
DESCRIPTOR.message_types_by_name['GeoTile'] = _GEOTILE

ClusteredPoint = _reflection.GeneratedProtocolMessageType('ClusteredPoint', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTEREDPOINT,
  __module__ = 'clustering_pb2'
  # @@protoc_insertion_point(class_scope:orbb.ClusteredPoint)
  ))
_sym_db.RegisterMessage(ClusteredPoint)

Clusters = _reflection.GeneratedProtocolMessageType('Clusters', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTERS,
  __module__ = 'clustering_pb2'
  # @@protoc_insertion_point(class_scope:orbb.Clusters)
  ))
_sym_db.RegisterMessage(Clusters)

GeoTile = _reflection.GeneratedProtocolMessageType('GeoTile', (_message.Message,), dict(
  DESCRIPTOR = _GEOTILE,
  __module__ = 'clustering_pb2'
  # @@protoc_insertion_point(class_scope:orbb.GeoTile)
  ))
_sym_db.RegisterMessage(GeoTile)


# @@protoc_insertion_point(module_scope)
