class End_2_End_Params:
    GT_FOLDER_KEY = "gt_folder"
    PRED_ROIS_FILE_KEY = "predictions_rois_file"
    MIN_SIZE_KEY = "min_size"
    IOU_THRESHOLD_KEY = "iou_threshold"
    SELECTED_CLASSES_KEY = "selected_classes"
    BASE_OUTPUT_PATH_KEY = "base_output_path"
    DELTA_PERC_ARR_KEY = "delta_perc_arr"
    FTP_OUTPUT_PATH_KEY = "ftp_output_path"
    CLASSIF_IMG_DIM_KEY = "classif_img_dim"
    NR_EPOCHS_KEY = "nr_epochs"

    TRAIN_PREDS_FILE_KEY = "train_preds_file"
    TRAIN_GT_FOLDER_KEY = "train_gt_folder"
    TEST_PREDS_FILE_KEY = "test_preds_file"
    TEST_GT_FOLDER_KEY = "test_gt_folder"
    OUTPUT_PATH_KEY = "output_path"
    DATASET_CLASSES_FILE_KEY = "dataset_classes_file"
    EVALUATE_CLASSES_FILE_KEY = "evaluate_classes_file"

    DATASET_FOLDER_NAME = "dataset"
    TRAIN_DATASET_FOLDER_NAME = "train_dataset"
    TRAIN_TEMP_DATASET_FOLDER_NAME = "train_temp_dataset"
    TEST_DATASET_FOLDER_NAME = "test_dataset"

    BASE_PATH_KEY = "base_path"
    IMG_DIM_KEY = "img_dim"
    NR_IMAGES_PER_CLASS_KEY = "nr_images_per_class"
    AUGMENT_STRATEGIES_KEY = "augment_strategies"
    FLIP_KEY = "flip"
    ROTATE_CW_KEY = "rotate_cw"
    ROTATE_CCW_KEY = "rotate_ccw"
    SUFFIX_KEY = "suffix"
    WITH_VP_CROP_KEY = "with_vp_crop"
    SPLIT_TRAIN_TEST_BY_SEQ_ID_KEY = "split_train_test_by_seq_id"
    SQUARE_IMAGE_KEY = "square_image"
    KEEP_ASPECT_KEY = "keep_aspect"

    NETWORK_FOLDER_NAME = "network"
    WEIGHTS_FOLDER_NAME = "weights"
    WEIGHTS_FILE_NAME = "weights.h5"

    PROCESSED_FOLDER_NAME = "processed"
    PARAMS_FOLDER_NAME = "params"
    MODEL_PARAMS_FILE_NAME = "model_params.json"

    PREDICTIONS_FOLDER_NAME = "predictions"
    TRAIN_PREDS_FILE_NAME = "train_preds.pkl"
    TEST_PREDS_FILE_NAME = "test_preds.pkl"

    BEST_THRESHOLDS_FOLDER_NAME = "best_thresholds"
    BEST_THRESHOLDS_FILE_NAME = "best_thresholds.json"
    ROIS_FILE_NAME = "rois.bin"

    POSTPROCESS_FOLDER_NAME = "postprocess"
    TRAIN_FOLDER_NAME = "train"
    TEST_FOLDER_NAME = "test"

    RESULTS_FOLDER_NAME = "results"
    STATISTICS_FILE_NAME = "statistics.json"
    BEST_PATH_FILE_NAME = "best_results.txt"
