import orbb_definitions_pb2

COMBINED_SPEED_LIMITS = [
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_5_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_10_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_15_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_20_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_25_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_30_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_35_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_40_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_45_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_50_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_55_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_60_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_65_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_70_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_75_US,
    orbb_definitions_pb2.SPEED_LIMIT_TRUCKS_80_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_5_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_10_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_15_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_20_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_25_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_30_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_35_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_40_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_45_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_50_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_55_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_60_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_65_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_70_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_75_US,
    orbb_definitions_pb2.SPEED_LIMIT_MINIMUM_80_US
]
