#!/bin/bash

# This script file is where you setup and execute your job inside your docker.  The following
# is the parsing of all available arguements that you can receive from the process that
# runs this script.  They are take directly from the values you supply when you submit a
# custom job. It is recommended not to change the following and to continue to the end of the
# file to add your script code.  Refer to the --help for a description of the arguements.

# Default values
CONFIG_FILE=NONE
DATA_DIR=NONE
LOG_DIR=NONE
MODEL_DIR=NONE
PREV_MODEL_PATH=NONE
IS_MEMCHECK=FALSE
declare -a EXTRA_ARGS

# Parsing command line arguments:
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -h|--help)
    echo "Usage: runCust [run_options]"
    echo "Options:"
    echo "  -c|--configFile <config> - which configuration file to use (default NONE)"
    echo "  -d|--dataDir <path> - directory path to input files (default NONE)"
    echo "  -l|--logDir <path> - directory path to save the log files (default NONE)"
    echo "  -m|--modelDir <path> - directory path to save the model files (default NONE)"
    echo "  --memCheck - start job in memcheck mode (default FALSE)"
    exit 1
    ;;
    -c|--configFile)
    CONFIG_FILE="$2"
    shift # pass argument
    ;;
    -d|--dataDir)
    DATA_DIR="$2"
    shift # pass argument
    ;;
    -l|--logDir)
    LOG_DIR="$2"
    shift # pass argument
    ;;
    -m|--modelDir)
    MODEL_DIR="$2"
    shift # pass argument
    ;;
    --memCheck)
    IS_MEMCHECK=TRUE
    ;;
    *)
    EXTRA_ARGS=("$@")
    break
    ;;
esac
shift # past argument or value
done

# Prints out the arguments that were passed into the script
echo "runCust: CONFIG_FILE=$CONFIG_FILE"
echo "runCust: DATA_DIR=$DATA_DIR"
echo "runCust: LOG_DIR=$LOG_DIR"
echo "runCust: MODEL_DIR=$MODEL_DIR"
echo "runCust: IS_MEMCHECK=$IS_MEMCHECK"
echo "runCust: EXTRA_ARGS=${EXTRA_ARGS[*]}"

# TODO: Add your script code below here
