#!/bin/bash

# This script file is where you setup and execute your job inside your docker.  The following
# is the parsing of all available arguements that you can receive from the process that 
# runs this script.  They are take directly from the values you supply when you submit a
# custom job. It is recommended not to change the following and to continue to the end of the
# file to add your script code.  Refer to the --help for a description of the arguements.

# Default values
set -x
CONFIG_FILE=NONE
DATA_DIR=NONE
LOG_DIR=NONE
MODEL_DIR=NONE
PREV_MODEL_PATH=NONE
IS_MEMCHECK=FALSE
EXTRA_ARGS=
GPU=0

# Parsing command line arguments:
while [[ $# > 0 ]]
do
key="$1"

case $key in
    -h|--help)
    echo "Usage: toolkit-execute [run_options]"
    echo "Options:"
    echo "  -c|--configFile <config> - which configuration file to use (default NONE)"
    echo "  -d|--dataDir <path> - directory path to input files (default NONE)"
    echo "  -l|--logDir <path> - directory path to save the log files (default NONE)"
    echo "  -m|--modelDir <path> - directory path to save the model files (default NONE)"
    echo "  --memCheck - start job in memcheck mode (default FALSE)"
    exit 1
    ;;
    -c|--configFile)
    CONFIG_FILE="$2"
    shift # pass argument
    ;;
    -d|--dataDir)
    DATA_DIR="$2"
    shift # pass argument
    ;;
    -l|--logDir)
    LOG_DIR="$2"
    shift # pass argument
    ;;
    -m|--modelDir)
    MODEL_DIR="$2"
    shift # pass argument
    ;;
    -g|--gpu)
    GPU="$2"
    shift # pass argument
    ;;
    --memCheck)
    IS_MEMCHECK=TRUE
    ;;
    *)
    EXTRA_ARGS="$@"
    break
    ;;
esac
shift # past argument or value
done

# Prints out the arguments that were passed into the script
echo "toolkit-execute: CONFIG_FILE=$CONFIG_FILE"
echo "toolkit-execute: DATA_DIR=$DATA_DIR"
echo "toolkit-execute: LOG_DIR=$LOG_DIR"
echo "toolkit-execute: MODEL_DIR=$MODEL_DIR"
echo "toolkit-execute: IS_MEMCHECK=$IS_MEMCHECK"
echo "toolkit-execute: EXTRA_ARGS=$EXTRA_ARGS"

# TODO: Add your script code below here
CONFIGB=$(basename "$CONFIG_FILE")
CONFIG_DIR=$(dirname "$CONFIG_FILE")
CONFIG_EXT="${CONFIGB##*.}"
CONFIG_NAME="${CONFIGB%.*}"
if [[ ${CONFIG_EXT} == "py" ]] ; then
    cd ${CONFIG_DIR} && python ${CONFIGB} --gpu ${GPU} --dataDir ${DATA_DIR} --modelDir ${MODEL_DIR} --logDir ${LOG_DIR} ${EXTRA_ARGS} || exit 1
else
    cmd="${CONFIG_FILE} --gpu ${GPU} --dataDir ${DATA_DIR} --modelDir ${MODEL_DIR} --logDir ${LOG_DIR} ${EXTRA_ARGS}"
    ${cmd} || exit 1
fi
